import Foundation

/// The four pieces every Curvy client needs, bundled together so they
/// can be distributed as a single base64 string over Signal/iMessage.
///
/// ```
/// {
///   "v": 1,
///   "token": "github_pat_…",
///   "roomKey": "<base64-32-bytes>",
///   "owner": "kumamaki",
///   "repo": "curvy-room"
/// }
/// ```
///
/// Generated by `scripts/mint-invite.sh`, decoded on paste in
/// `InviteView`, validated by `GitHubClient.verifyAccess(invite:)`.
struct Invite: Codable, Equatable, Sendable {
    let v: Int
    let token: String
    let roomKey: String
    let owner: String
    let repo: String

    static let currentVersion = 1

    /// Raw 32-byte room key. Decoded from the base64 `roomKey` field.
    /// Kept as a computed property so we never accidentally serialise
    /// the raw bytes.
    var roomKeyData: Data? {
        Data(base64Encoded: roomKey)
    }

    enum DecodeError: Error, CustomStringConvertible {
        case notBase64
        case malformedJSON
        case unsupportedVersion(Int)
        case missingFields
        case invalidRoomKey

        var description: String { userFacing }

        var userFacing: String {
            switch self {
            case .notBase64: "That doesn't look like an invite — paste the full base64 string."
            case .malformedJSON: "The invite is corrupted. Ask kumamaki for a fresh one."
            case .unsupportedVersion(let v): "This invite is version \(v); this app only understands version \(currentVersion)."
            case .missingFields: "The invite is missing required fields."
            case .invalidRoomKey: "The room key in this invite isn't a valid 32-byte base64 string."
            }
        }
    }

    /// Decode an invite from a single base64 string (the form shared
    /// over Signal). Strips whitespace before decoding because pasted
    /// blobs often arrive with line wraps.
    static func decode(_ raw: String) throws -> Invite {
        let cleaned = raw
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "\n", with: "")
            .replacingOccurrences(of: " ", with: "")
        guard let payload = Data(base64Encoded: cleaned) else {
            throw DecodeError.notBase64
        }
        let invite: Invite
        do {
            invite = try JSONDecoder().decode(Invite.self, from: payload)
        } catch {
            throw DecodeError.malformedJSON
        }
        guard invite.v == currentVersion else {
            throw DecodeError.unsupportedVersion(invite.v)
        }
        guard !invite.token.isEmpty,
              !invite.owner.isEmpty,
              !invite.repo.isEmpty else {
            throw DecodeError.missingFields
        }
        guard let key = invite.roomKeyData, key.count == 32 else {
            throw DecodeError.invalidRoomKey
        }
        return invite
    }

    /// Encode to the wire form. Used by `mint-invite.sh` callers and
    /// in tests; not used in the running app.
    func encode() throws -> String {
        let json = try JSONEncoder().encode(self)
        return json.base64EncodedString()
    }
}
